// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtKQwwPegnIUhnd7CP6QJA_83W3T7uZ4',
    appId: '1:469357945981:web:2adaa38ea9ff812dc7fd14',
    messagingSenderId: '469357945981',
    projectId: 'systemlog-59857',
    authDomain: 'systemlog-59857.firebaseapp.com',
    storageBucket: 'systemlog-59857.firebasestorage.app',
    measurementId: 'G-YTJFXS669X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbAbcCkPHB7J95Dm8UmORugbD9jqupIfQ',
    appId: '1:469357945981:android:d653afa1e42134d3c7fd14',
    messagingSenderId: '469357945981',
    projectId: 'systemlog-59857',
    storageBucket: 'systemlog-59857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjdwP892goIXZhdIVQYKXLqfAOZQ2KWkk',
    appId: '1:469357945981:ios:e0a6c28d5322f8f5c7fd14',
    messagingSenderId: '469357945981',
    projectId: 'systemlog-59857',
    storageBucket: 'systemlog-59857.firebasestorage.app',
    iosBundleId: 'com.example.pages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjdwP892goIXZhdIVQYKXLqfAOZQ2KWkk',
    appId: '1:469357945981:ios:e0a6c28d5322f8f5c7fd14',
    messagingSenderId: '469357945981',
    projectId: 'systemlog-59857',
    storageBucket: 'systemlog-59857.firebasestorage.app',
    iosBundleId: 'com.example.pages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJtKQwwPegnIUhnd7CP6QJA_83W3T7uZ4',
    appId: '1:469357945981:web:5fe9e52c5e9d93f1c7fd14',
    messagingSenderId: '469357945981',
    projectId: 'systemlog-59857',
    authDomain: 'systemlog-59857.firebaseapp.com',
    storageBucket: 'systemlog-59857.firebasestorage.app',
    measurementId: 'G-XBPD86P3WG',
  );
}
